oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/robbyrussell.omp.json" | Invoke-Expression
Set-Alias -Name dk -Value C:\commands\docker.bat
Set-Alias -Name gac -Value C:\commands\git-add-commit.bat
Set-Alias -Name gbc -Value C:\commands\git-checkout-change-branch.bat
Set-Alias -Name gbd -Value C:\commands\git-branch-delete.bat
Set-Alias -Name gbam -Value C:\commands\git-branch-auto-merge.bat
Set-Alias -Name gbm -Value C:\commands\git-branch-merge.bat
Set-Alias -Name gbn -Value C:\commands\git-checkout-new-branch.bat
Set-Alias -Name gf -Value C:\commands\git-fetch.bat
Set-Alias -Name girao -Value C:\commands\git-init-remote-add-origin.bat
Set-Alias -Name gpsh -Value C:\commands\git-push.bat
Set-Alias -Name gpul -Value C:\commands\git-pull.bat
Set-Alias -Name kinghost -Value C:\commands\kinghost.bat
Set-Alias -Name nr -Value C:\commands\npm-run.bat
Set-Alias -Name nrb -Value C:\commands\npm-run-build.bat
Set-Alias -Name nrd -Value C:\commands\npm-run-dev.bat
Set-Alias -Name ns -Value C:\commands\npm-start.bat
Set-Alias -Name nt -Value C:\commands\npm-test.bat
Set-Alias -Name pa -Value C:\commands\php-artisan.bat
Set-Alias -Name pads -Value C:\commands\php-artisan-db-seed.bat
Set-Alias -Name pam -Value C:\commands\php-artisan-migrate.bat
Set-Alias -Name pamf -Value C:\commands\php-artisan-migrate-fresh.bat
Set-Alias -Name pamfs -Value C:\commands\php-artisan-migrate-fresh-seed.bat
Set-Alias -Name pamr -Value C:\commands\php-artisan-migrate-rollback.bat
Set-Alias -Name paqw -Value C:\commands\php-artisan-queue-work.bat
Set-Alias -Name pas -Value C:\commands\php-artisan-serve.bat
Set-Alias -Name pas8001 -Value C:\commands\php-artisan-serve-port-8001.bat
Set-Alias -Name pas8002 -Value C:\commands\php-artisan-serve-port-8002.bat
Set-Alias -Name php7 -Value C:\commands\run-php-7.bat
Set-Alias -Name pn -Value C:\commands\pnpm.bat
Set-Alias -Name pna -Value C:\commands\pnpm-add.bat
Set-Alias -Name pni -Value C:\commands\pnpm-install.bat
Set-Alias -Name pnr -Value C:\commands\pnpm-remove.bat
Set-Alias -Name pnrd -Value C:\commands\pnpm-run-dev.bat
Set-Alias -Name pnu -Value C:\commands\pnpm-update.bat
Set-Alias -Name pnt -Value C:\commands\pnpm-test.bat
Set-Alias -Name pnx -Value C:\commands\pnpm-dlx.bat
Set-Alias -Name wip -Value C:\commands\wip.bat
Set-Alias -Name wipai -Value C:\commands\wipai.bat
Set-Alias -Name zig -Value C:\commands\zig.bat